### ISSUE TITLE
[Planner] Neural Helix wrong selection logic

### ISSUE THREAD

**Issue by coldasicee** [EXILIUM-Tracker/i18n#27]
When selecting the Neural Helix I thought the checkmarks were meant to be what you already have. So I selected up to 4-02. It ends up showing the materials need from 1-02 up to 4-02, not 5-02 up to 6-02. And you can't select the Evolved nodes you already have.
I tried selecting the inverse (5-02 and 6-02) so it would show the materials needed for them but the website won't let me.

Here is an image of how it's looking:

![Image](https://github.com/user-attachments/assets/794d36a8-53a2-454b-b257-576edf74c6ec)

**Comment by codewithmei** [comment]
> When selecting the Neural Helix I thought the checkmarks were meant to be what you already have. So I selected up to 4-02. It ends up showing the materials need from 1-02 up to 4-02, not 5-02 up to 6-02. And you can't select the Evolved nodes you already have. I tried selecting the inverse (5-02 and 6-02) so it would show the materials needed for them but the website won't let me.
  
  Currently, the checkmarks in the Neural Helix section represent nodes you want to include in your planner calculations, not nodes you already have in-game. The website is calculating materials needed to unlock those selected nodes.
  
  I've addressed this issue in my latest update with two key improvements:
  1. Added a tooltip that clarifies what the checkmarks represent: "Checked nodes indicate which Neural Helix nodes you want to unlock. The planner will calculate materials needed for all selected nodes."
  2. Fixed the selection logic to allow selecting any main node directly without requiring previous nodes to be selected first

If you still encounter any issues after this update, I'd appreciate if you could attach an exported backup from the Settings page > Backups tab > Export Backups button.

**Comment by coldasicee** [comment]
> > When selecting the Neural Helix I thought the checkmarks were meant to be what you already have. So I selected up to 4-02. It ends up showing the materials need from 1-02 up to 4-02, not 5-02 up to 6-02. And you can't select the Evolved nodes you already have. I tried selecting the inverse (5-02 and 6-02) so it would show the materials needed for them but the website won't let me.
> 
> Currently, the checkmarks in the Neural Helix section represent nodes you want to include in your planner calculations, not nodes you already have in-game. The website is calculating materials needed to unlock those selected nodes.
> 
> I've addressed this issue in my latest update with two key improvements:
> 
> 1. Added a tooltip that clarifies what the checkmarks represent: "Checked nodes indicate which Neural Helix nodes you want to unlock. The planner will calculate materials needed for all selected nodes."
> 2. Fixed the selection logic to allow selecting any main node directly without requiring previous nodes to be selected first
> 
> If you still encounter any issues after this update, I'd appreciate if you could attach an exported backup from the Settings page > Backups tab > Export Backups button.

Oh its been fixed, thank you! Because before you couldn't select in the inverse order, it was greyed out. For example, if I wanted to select 6-02 and 5-02.

We still can't select the side nodes yet, though. (i.e 2-01 and 2-03)

**Comment by coldasicee** [comment]
Here is another example, my KK is currently this way:

![Image](https://github.com/user-attachments/assets/c40ae278-e0d4-4bf0-8aeb-74192037deca)

But I can't select the 6-03 node on the Planner:

![Image](https://github.com/user-attachments/assets/64e34500-6805-4479-a96e-fc3ed30a1206)

**Comment by codewithmei** [comment]
> We still can't select the side nodes yet, though. (i.e 2-01 and 2-03)

I've fixed this issue. Let me know if it's still occurring on your end.

**Comment by coldasicee** [comment]
> > We still can't select the side nodes yet, though. (i.e 2-01 and 2-03)
> 
> I've fixed this issue. Let me know if it's still occurring on your end.

yep, everything has been fixed, thank you very much. I'll probably start helping the project by translating it to portuguese if no one else is doing it.
